/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gilberto_a_robot_arm3.glb -T -t -D 
Files: ./public/models/gilberto_a_robot_arm3.glb [594.28KB] > /Users/pampanie/dev/projects/3dworks/robot/robotop/gilberto_a_robot_arm3-transformed.glb [99.71KB] (83%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_Mesh001: THREE.SkinnedMesh
    Object_Mesh002: THREE.SkinnedMesh
    Object_Mesh003: THREE.SkinnedMesh
    Object_Mesh004: THREE.SkinnedMesh
    Object_Mesh005: THREE.SkinnedMesh
    Object_Mesh006: THREE.SkinnedMesh
    Object_Mesh007: THREE.SkinnedMesh
    Object_Mesh008: THREE.SkinnedMesh
    Object_Mesh009: THREE.SkinnedMesh
    Object_Mesh010: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/gilberto_a_robot_arm3-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_Mesh001.geometry} material={nodes.Object_Mesh001.material} skeleton={nodes.Object_Mesh001.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh002.geometry} material={nodes.Object_Mesh002.material} skeleton={nodes.Object_Mesh002.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh003.geometry} material={nodes.Object_Mesh003.material} skeleton={nodes.Object_Mesh003.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh004.geometry} material={nodes.Object_Mesh004.material} skeleton={nodes.Object_Mesh004.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh005.geometry} material={nodes.Object_Mesh005.material} skeleton={nodes.Object_Mesh005.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh006.geometry} material={nodes.Object_Mesh006.material} skeleton={nodes.Object_Mesh006.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh007.geometry} material={nodes.Object_Mesh007.material} skeleton={nodes.Object_Mesh007.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh008.geometry} material={nodes.Object_Mesh008.material} skeleton={nodes.Object_Mesh008.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh009.geometry} material={nodes.Object_Mesh009.material} skeleton={nodes.Object_Mesh009.skeleton} />
      <skinnedMesh geometry={nodes.Object_Mesh010.geometry} material={nodes.Object_Mesh010.material} skeleton={nodes.Object_Mesh010.skeleton} />
    </group>
  )
}

useGLTF.preload('/gilberto_a_robot_arm3-transformed.glb')
