/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gilberto_a_robot_arm5.glb -T -t -D 
Files: ./public/models/gilberto_a_robot_arm5.glb [653.94KB] > /Users/pampanie/dev/projects/3dworks/robot/robotop/gilberto_a_robot_arm5-transformed.glb [103.58KB] (84%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Claw_Pivot_L_013_MESH001_HITBOX: THREE.Mesh
    Claw_Pivot_R_011_MESH001_HITBOX_HITBOX: THREE.Mesh
    Claw_Pivot_L_013_MESH001: THREE.SkinnedMesh
    Claw_Pivot_R_011_MESH001: THREE.SkinnedMesh
    J_Base_Pivot_Rot_02_MESH001: THREE.SkinnedMesh
    J_Base_Rot_01_MESH001: THREE.SkinnedMesh
    J_Claw_Base_Rot_07_MESH001: THREE.SkinnedMesh
    J_Claw_Both_Rot_09_MESH001: THREE.SkinnedMesh
    J_Elbow_03_MESH001: THREE.SkinnedMesh
    J_Helper_01_08_MESH001: THREE.SkinnedMesh
    J_Upper_Pivot_05_MESH001: THREE.SkinnedMesh
    Mech_Root_00_MESH001: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/gilberto_a_robot_arm5-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <primitive object={nodes.neutral_bone} />
      <mesh geometry={nodes.Claw_Pivot_L_013_MESH001_HITBOX.geometry} material={nodes.Claw_Pivot_L_013_MESH001_HITBOX.material} position={[23.873, 126.438, 327.714]} scale={[35.634, 133.303, 14.717]} />
      <mesh geometry={nodes.Claw_Pivot_R_011_MESH001_HITBOX_HITBOX.geometry} material={nodes.Claw_Pivot_R_011_MESH001_HITBOX_HITBOX.material} position={[-23.871, 126.438, 327.714]} scale={[35.668, 133.303, 14.717]} />
      <skinnedMesh geometry={nodes.Claw_Pivot_L_013_MESH001.geometry} material={nodes.Claw_Pivot_L_013_MESH001.material} skeleton={nodes.Claw_Pivot_L_013_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.Claw_Pivot_R_011_MESH001.geometry} material={nodes.Claw_Pivot_R_011_MESH001.material} skeleton={nodes.Claw_Pivot_R_011_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Base_Pivot_Rot_02_MESH001.geometry} material={nodes.J_Base_Pivot_Rot_02_MESH001.material} skeleton={nodes.J_Base_Pivot_Rot_02_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Base_Rot_01_MESH001.geometry} material={nodes.J_Base_Rot_01_MESH001.material} skeleton={nodes.J_Base_Rot_01_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Claw_Base_Rot_07_MESH001.geometry} material={nodes.J_Claw_Base_Rot_07_MESH001.material} skeleton={nodes.J_Claw_Base_Rot_07_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Claw_Both_Rot_09_MESH001.geometry} material={nodes.J_Claw_Both_Rot_09_MESH001.material} skeleton={nodes.J_Claw_Both_Rot_09_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Elbow_03_MESH001.geometry} material={nodes.J_Elbow_03_MESH001.material} skeleton={nodes.J_Elbow_03_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Helper_01_08_MESH001.geometry} material={nodes.J_Helper_01_08_MESH001.material} skeleton={nodes.J_Helper_01_08_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.J_Upper_Pivot_05_MESH001.geometry} material={nodes.J_Upper_Pivot_05_MESH001.material} skeleton={nodes.J_Upper_Pivot_05_MESH001.skeleton} />
      <skinnedMesh geometry={nodes.Mech_Root_00_MESH001.geometry} material={nodes.Mech_Root_00_MESH001.material} skeleton={nodes.Mech_Root_00_MESH001.skeleton} />
    </group>
  )
}

useGLTF.preload('/gilberto_a_robot_arm5-transformed.glb')
