/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gilberto_a_robot_arm4.glb -T -t -D 
Files: ./public/models/gilberto_a_robot_arm4.glb [585.86KB] > /Users/pampanie/dev/projects/3dworks/robot/robotop/gilberto_a_robot_arm4-transformed.glb [77.44KB] (87%)
*/

import * as THREE from 'three';
import { useRef, useState } from 'react';
import { useFrame, useGraph } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Claw_Pivot_L_013_MESH: THREE.SkinnedMesh;
		Claw_Pivot_R_011_MESH: THREE.SkinnedMesh;
		J_Base_Pivot_Rot_02_MESH: THREE.SkinnedMesh;
		J_Base_Rot_01_MESH: THREE.SkinnedMesh;
		J_Claw_Base_Rot_07_MESH: THREE.SkinnedMesh;
		J_Claw_Both_Rot_09_MESH: THREE.SkinnedMesh;
		J_Elbow_03_MESH: THREE.SkinnedMesh;
		J_Helper_01_08_MESH: THREE.SkinnedMesh;
		J_Upper_Pivot_05_MESH: THREE.SkinnedMesh;
		Mech_Root_00_MESH: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {};
	animations: THREE.AnimationClip[];
};

export function RobotArm(props: JSX.IntrinsicElements['group']) {
	const { scene } = useGLTF('models/gilberto_a_robot_arm4-transformed.glb');
	const clone = SkeletonUtils.clone(scene);
	const { nodes, materials } = useGraph(clone) as GLTFResult;
	const [targetPosition, setTargetPosition] = useState(
		new THREE.Vector3(0, 0, 0)
	);
	const bones = (() => {
		const collectedBones: THREE.Bone[] = [];

		if (nodes._rootJoint) {
			const traverseBones = (bone: THREE.Bone) => {
				collectedBones.push(bone);

				if (bone.userData.rotationLimits) {
					console.log(
						'Rotation limits for',
						bone.name,
						':',
						bone.userData.rotationLimits
					);
				}

				bone.children.forEach((child) => {
					if (child instanceof THREE.Bone) {
						traverseBones(child);
					}
				});
			};

			traverseBones(nodes._rootJoint);
		}

		return collectedBones;
	})();

	console.log('Bones:', bones);

	const setBoneLimits = (
		bone: THREE.Bone,
		limits: { min: THREE.Vector3; max: THREE.Vector3 }
	) => {
		bone.userData.rotationLimits = {
			min: limits.min,
			max: limits.max,
		};
		console.log('Set rotation limits for', bone.name, ':', {
			min: limits.min,
			max: limits.max,
		});
	};

	const handleClick = (event: React.MouseEvent) => {
		console.log('Clicked on robot arm', event);
	};

	useFrame((_) => {
		const clawBone = bones.find((bone) => bone.name === 'J_Claw_Base_Rot_07');
		// console.log('found bone', clawBone);
		if (clawBone) {
			clawBone.rotateX(0.01);
		}
	});

	return (
		<group
			{...props}
			dispose={null}
			scale={[0.005, 0.005, 0.005]}
			onClick={handleClick}
		>
			<primitive object={nodes._rootJoint} />
			<skinnedMesh
				geometry={nodes.Claw_Pivot_L_013_MESH.geometry}
				material={nodes.Claw_Pivot_L_013_MESH.material}
				skeleton={nodes.Claw_Pivot_L_013_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Claw_Pivot_R_011_MESH.geometry}
				material={nodes.Claw_Pivot_R_011_MESH.material}
				skeleton={nodes.Claw_Pivot_R_011_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Base_Pivot_Rot_02_MESH.geometry}
				material={nodes.J_Base_Pivot_Rot_02_MESH.material}
				skeleton={nodes.J_Base_Pivot_Rot_02_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Base_Rot_01_MESH.geometry}
				material={nodes.J_Base_Rot_01_MESH.material}
				skeleton={nodes.J_Base_Rot_01_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Claw_Base_Rot_07_MESH.geometry}
				material={nodes.J_Claw_Base_Rot_07_MESH.material}
				skeleton={nodes.J_Claw_Base_Rot_07_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Claw_Both_Rot_09_MESH.geometry}
				material={nodes.J_Claw_Both_Rot_09_MESH.material}
				skeleton={nodes.J_Claw_Both_Rot_09_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Elbow_03_MESH.geometry}
				material={nodes.J_Elbow_03_MESH.material}
				skeleton={nodes.J_Elbow_03_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Helper_01_08_MESH.geometry}
				material={nodes.J_Helper_01_08_MESH.material}
				skeleton={nodes.J_Helper_01_08_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.J_Upper_Pivot_05_MESH.geometry}
				material={nodes.J_Upper_Pivot_05_MESH.material}
				skeleton={nodes.J_Upper_Pivot_05_MESH.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Mech_Root_00_MESH.geometry}
				material={nodes.Mech_Root_00_MESH.material}
				skeleton={nodes.Mech_Root_00_MESH.skeleton}
			/>
		</group>
	);
}

useGLTF.preload('models/gilberto_a_robot_arm4-transformed.glb');
