/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gilberto_a_robot_arm3.glb -T -t -D 
Files: ./public/models/gilberto_a_robot_arm3.glb [585.86KB] > /Users/pampanie/dev/projects/3dworks/robot/robotop/gilberto_a_robot_arm3-transformed.glb [77.44KB] (87%)
*/

import * as THREE from 'three';
import { useRef, useState } from 'react';
import { useFrame, useGraph } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { GLTF, SkeletonUtils } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		Object_Mesh001: THREE.SkinnedMesh;
		Object_Mesh002: THREE.SkinnedMesh;
		Object_Mesh003: THREE.SkinnedMesh;
		Object_Mesh004: THREE.SkinnedMesh;
		Object_Mesh005: THREE.SkinnedMesh;
		Object_Mesh006: THREE.SkinnedMesh;
		Object_Mesh007: THREE.SkinnedMesh;
		Object_Mesh008: THREE.SkinnedMesh;
		Object_Mesh009: THREE.SkinnedMesh;
		Object_Mesh010: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {};
	animations: THREE.AnimationClip[];
};

export function RobotArm(props: JSX.IntrinsicElements['group']) {
	const { scene } = useGLTF('models/gilberto_a_robot_arm3-transformed.glb');
	const clone = SkeletonUtils.clone(scene);
	const { nodes, materials } = useGraph(clone) as GLTFResult;
	const [targetPosition, setTargetPosition] = useState(
		new THREE.Vector3(0, 0, 0)
	);
	const bones = (() => {
		const collectedBones: THREE.Bone[] = [];

		if (nodes._rootJoint) {
			const traverseBones = (bone: THREE.Bone) => {
				collectedBones.push(bone);

				if (bone.userData.rotationLimits) {
					console.log(
						'Rotation limits for',
						bone.name,
						':',
						bone.userData.rotationLimits
					);
				}

				bone.children.forEach((child) => {
					if (child instanceof THREE.Bone) {
						traverseBones(child);
					}
				});
			};

			traverseBones(nodes._rootJoint);
		}

		return collectedBones;
	})();

	console.log('Bones:', bones);

	const setBoneLimits = (
		bone: THREE.Bone,
		limits: { min: THREE.Vector3; max: THREE.Vector3 }
	) => {
		bone.userData.rotationLimits = {
			min: limits.min,
			max: limits.max,
		};
		console.log('Set rotation limits for', bone.name, ':', {
			min: limits.min,
			max: limits.max,
		});
	};

	const handleClick = (event: React.MouseEvent) => {
		console.log('Clicked on robot arm', event);
	};

	useFrame((_) => {});

	return (
		<group
			{...props}
			dispose={null}
			scale={[0.005, 0.005, 0.005]}
			onClick={handleClick}
		>
			<primitive object={nodes._rootJoint} />
			<skinnedMesh
				geometry={nodes.Object_Mesh001.geometry}
				material={nodes.Object_Mesh001.material}
				skeleton={nodes.Object_Mesh001.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh002.geometry}
				material={nodes.Object_Mesh002.material}
				skeleton={nodes.Object_Mesh002.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh003.geometry}
				material={nodes.Object_Mesh003.material}
				skeleton={nodes.Object_Mesh003.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh004.geometry}
				material={nodes.Object_Mesh004.material}
				skeleton={nodes.Object_Mesh004.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh005.geometry}
				material={nodes.Object_Mesh005.material}
				skeleton={nodes.Object_Mesh005.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh006.geometry}
				material={nodes.Object_Mesh006.material}
				skeleton={nodes.Object_Mesh006.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh007.geometry}
				material={nodes.Object_Mesh007.material}
				skeleton={nodes.Object_Mesh007.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh008.geometry}
				material={nodes.Object_Mesh008.material}
				skeleton={nodes.Object_Mesh008.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh009.geometry}
				material={nodes.Object_Mesh009.material}
				skeleton={nodes.Object_Mesh009.skeleton}
			/>
			<skinnedMesh
				geometry={nodes.Object_Mesh010.geometry}
				material={nodes.Object_Mesh010.material}
				skeleton={nodes.Object_Mesh010.skeleton}
			/>
		</group>
	);
}

useGLTF.preload('models/gilberto_a_robot_arm3-transformed.glb');
